### ISSUE TITLE
Don't Include Proof General in this Repo

### ISSUE THREAD

**Issue by bkc39** [bkc39/Coq311#9]
It is ridiculous to have the entirety of Proof General in `courseware/.emacs.d`. What we should do is either:
- Add a setup script to download an configure it on VM startup.
- Update `pkg.el` to download the package to the relevant directory and add the load to the config.

Unfortunately Proof General isn't on MELPA so we have to do one of these things. But this will drastically reduce the size of this repo. More importantly it reduces it to code we actually wrote =)

**Comment by bkc39** [comment]
If you approve of #11 we can consider this closed.

**Comment by bennn** [comment]
al-right
